package com.senso.dao;

import com.senso.model.Schoolclass;
import com.senso.model.SchoolclassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolclassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SchoolClass
     *
     * @mbg.generated
     */
    long countByExample(SchoolclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SchoolClass
     *
     * @mbg.generated
     */
    int deleteByExample(SchoolclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SchoolClass
     *
     * @mbg.generated
     */
    int insert(Schoolclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SchoolClass
     *
     * @mbg.generated
     */
    int insertSelective(Schoolclass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SchoolClass
     *
     * @mbg.generated
     */
    List<Schoolclass> selectByExample(SchoolclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SchoolClass
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Schoolclass record, @Param("example") SchoolclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SchoolClass
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Schoolclass record, @Param("example") SchoolclassExample example);
}