package com.senso.boot.mapper;

import com.senso.boot.entity.DeptManager;
import com.senso.boot.entity.DeptManagerExample;
import com.senso.boot.entity.DeptManagerKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DeptManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    long countByExample(DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int deleteByExample(DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(DeptManagerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int insert(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int insertSelective(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    List<DeptManager> selectByExample(DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    DeptManager selectByPrimaryKey(DeptManagerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DeptManager record, @Param("example") DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DeptManager record, @Param("example") DeptManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeptManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_manager
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeptManager record);
}