package com.senso.boot.mapper;

import com.senso.boot.entity.DeptEmp;
import com.senso.boot.entity.DeptEmpExample;
import com.senso.boot.entity.DeptEmpKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DeptEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    long countByExample(DeptEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    int deleteByExample(DeptEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(DeptEmpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    int insert(DeptEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    int insertSelective(DeptEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    List<DeptEmp> selectByExample(DeptEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    DeptEmp selectByPrimaryKey(DeptEmpKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DeptEmp record, @Param("example") DeptEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DeptEmp record, @Param("example") DeptEmpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DeptEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DeptEmp record);
}