package com.senso.boot.mapper;

import com.senso.boot.entity.Titles;
import com.senso.boot.entity.TitlesExample;
import com.senso.boot.entity.TitlesKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TitlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    long countByExample(TitlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int deleteByExample(TitlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TitlesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int insert(Titles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int insertSelective(Titles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    List<Titles> selectByExample(TitlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    Titles selectByPrimaryKey(TitlesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Titles record, @Param("example") TitlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Titles record, @Param("example") TitlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Titles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Titles record);
}