package com.senso.model;

public class Schoolclass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SchoolClass.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SchoolClass.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SchoolClass.teacher_id
     *
     * @mbg.generated
     */
    private Integer teacher_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SchoolClass.id
     *
     * @return the value of SchoolClass.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SchoolClass.id
     *
     * @param id the value for SchoolClass.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SchoolClass.name
     *
     * @return the value of SchoolClass.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SchoolClass.name
     *
     * @param name the value for SchoolClass.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SchoolClass.teacher_id
     *
     * @return the value of SchoolClass.teacher_id
     *
     * @mbg.generated
     */
    public Integer getTeacher_id() {
        return teacher_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SchoolClass.teacher_id
     *
     * @param teacher_id the value for SchoolClass.teacher_id
     *
     * @mbg.generated
     */
    public void setTeacher_id(Integer teacher_id) {
        this.teacher_id = teacher_id;
    }
}