package com.senso.boot.entity;

public class Departments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.dept_no
     *
     * @mbg.generated
     */
    private String dept_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column departments.dept_name
     *
     * @mbg.generated
     */
    private String dept_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.dept_no
     *
     * @return the value of departments.dept_no
     *
     * @mbg.generated
     */
    public String getDept_no() {
        return dept_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.dept_no
     *
     * @param dept_no the value for departments.dept_no
     *
     * @mbg.generated
     */
    public void setDept_no(String dept_no) {
        this.dept_no = dept_no == null ? null : dept_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column departments.dept_name
     *
     * @return the value of departments.dept_name
     *
     * @mbg.generated
     */
    public String getDept_name() {
        return dept_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column departments.dept_name
     *
     * @param dept_name the value for departments.dept_name
     *
     * @mbg.generated
     */
    public void setDept_name(String dept_name) {
        this.dept_name = dept_name == null ? null : dept_name.trim();
    }
}