package com.senso.boot.entity;

import java.util.ArrayList;
import java.util.List;

public class DepartmentsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table departments
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table departments
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table departments
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    public DepartmentsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table departments
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDept_noIsNull() {
            addCriterion("dept_no is null");
            return (Criteria) this;
        }

        public Criteria andDept_noIsNotNull() {
            addCriterion("dept_no is not null");
            return (Criteria) this;
        }

        public Criteria andDept_noEqualTo(String value) {
            addCriterion("dept_no =", value, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noNotEqualTo(String value) {
            addCriterion("dept_no <>", value, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noGreaterThan(String value) {
            addCriterion("dept_no >", value, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noGreaterThanOrEqualTo(String value) {
            addCriterion("dept_no >=", value, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noLessThan(String value) {
            addCriterion("dept_no <", value, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noLessThanOrEqualTo(String value) {
            addCriterion("dept_no <=", value, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noLike(String value) {
            addCriterion("dept_no like", value, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noNotLike(String value) {
            addCriterion("dept_no not like", value, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noIn(List<String> values) {
            addCriterion("dept_no in", values, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noNotIn(List<String> values) {
            addCriterion("dept_no not in", values, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noBetween(String value1, String value2) {
            addCriterion("dept_no between", value1, value2, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_noNotBetween(String value1, String value2) {
            addCriterion("dept_no not between", value1, value2, "dept_no");
            return (Criteria) this;
        }

        public Criteria andDept_nameIsNull() {
            addCriterion("dept_name is null");
            return (Criteria) this;
        }

        public Criteria andDept_nameIsNotNull() {
            addCriterion("dept_name is not null");
            return (Criteria) this;
        }

        public Criteria andDept_nameEqualTo(String value) {
            addCriterion("dept_name =", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameNotEqualTo(String value) {
            addCriterion("dept_name <>", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameGreaterThan(String value) {
            addCriterion("dept_name >", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameGreaterThanOrEqualTo(String value) {
            addCriterion("dept_name >=", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameLessThan(String value) {
            addCriterion("dept_name <", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameLessThanOrEqualTo(String value) {
            addCriterion("dept_name <=", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameLike(String value) {
            addCriterion("dept_name like", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameNotLike(String value) {
            addCriterion("dept_name not like", value, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameIn(List<String> values) {
            addCriterion("dept_name in", values, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameNotIn(List<String> values) {
            addCriterion("dept_name not in", values, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameBetween(String value1, String value2) {
            addCriterion("dept_name between", value1, value2, "dept_name");
            return (Criteria) this;
        }

        public Criteria andDept_nameNotBetween(String value1, String value2) {
            addCriterion("dept_name not between", value1, value2, "dept_name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table departments
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table departments
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}