package com.senso.boot.entity;

import java.util.Date;

public class DeptEmp extends DeptEmpKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_emp.from_date
     *
     * @mbg.generated
     */
    private Date from_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_emp.to_date
     *
     * @mbg.generated
     */
    private Date to_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_emp.from_date
     *
     * @return the value of dept_emp.from_date
     *
     * @mbg.generated
     */
    public Date getFrom_date() {
        return from_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_emp.from_date
     *
     * @param from_date the value for dept_emp.from_date
     *
     * @mbg.generated
     */
    public void setFrom_date(Date from_date) {
        this.from_date = from_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_emp.to_date
     *
     * @return the value of dept_emp.to_date
     *
     * @mbg.generated
     */
    public Date getTo_date() {
        return to_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_emp.to_date
     *
     * @param to_date the value for dept_emp.to_date
     *
     * @mbg.generated
     */
    public void setTo_date(Date to_date) {
        this.to_date = to_date;
    }
}