package com.senso.boot.entity;

public class DeptEmpKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_emp.emp_no
     *
     * @mbg.generated
     */
    private Integer emp_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_emp.dept_no
     *
     * @mbg.generated
     */
    private String dept_no;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_emp.emp_no
     *
     * @return the value of dept_emp.emp_no
     *
     * @mbg.generated
     */
    public Integer getEmp_no() {
        return emp_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_emp.emp_no
     *
     * @param emp_no the value for dept_emp.emp_no
     *
     * @mbg.generated
     */
    public void setEmp_no(Integer emp_no) {
        this.emp_no = emp_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_emp.dept_no
     *
     * @return the value of dept_emp.dept_no
     *
     * @mbg.generated
     */
    public String getDept_no() {
        return dept_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_emp.dept_no
     *
     * @param dept_no the value for dept_emp.dept_no
     *
     * @mbg.generated
     */
    public void setDept_no(String dept_no) {
        this.dept_no = dept_no == null ? null : dept_no.trim();
    }
}