package com.senso.boot.entity;

import java.util.Date;

public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.emp_no
     *
     * @mbg.generated
     */
    private Integer emp_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.birth_date
     *
     * @mbg.generated
     */
    private Date birth_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.first_name
     *
     * @mbg.generated
     */
    private String first_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.last_name
     *
     * @mbg.generated
     */
    private String last_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.hire_date
     *
     * @mbg.generated
     */
    private Date hire_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.emp_no
     *
     * @return the value of employees.emp_no
     *
     * @mbg.generated
     */
    public Integer getEmp_no() {
        return emp_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.emp_no
     *
     * @param emp_no the value for employees.emp_no
     *
     * @mbg.generated
     */
    public void setEmp_no(Integer emp_no) {
        this.emp_no = emp_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.birth_date
     *
     * @return the value of employees.birth_date
     *
     * @mbg.generated
     */
    public Date getBirth_date() {
        return birth_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.birth_date
     *
     * @param birth_date the value for employees.birth_date
     *
     * @mbg.generated
     */
    public void setBirth_date(Date birth_date) {
        this.birth_date = birth_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.first_name
     *
     * @return the value of employees.first_name
     *
     * @mbg.generated
     */
    public String getFirst_name() {
        return first_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.first_name
     *
     * @param first_name the value for employees.first_name
     *
     * @mbg.generated
     */
    public void setFirst_name(String first_name) {
        this.first_name = first_name == null ? null : first_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.last_name
     *
     * @return the value of employees.last_name
     *
     * @mbg.generated
     */
    public String getLast_name() {
        return last_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.last_name
     *
     * @param last_name the value for employees.last_name
     *
     * @mbg.generated
     */
    public void setLast_name(String last_name) {
        this.last_name = last_name == null ? null : last_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.gender
     *
     * @return the value of employees.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.gender
     *
     * @param gender the value for employees.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.hire_date
     *
     * @return the value of employees.hire_date
     *
     * @mbg.generated
     */
    public Date getHire_date() {
        return hire_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.hire_date
     *
     * @param hire_date the value for employees.hire_date
     *
     * @mbg.generated
     */
    public void setHire_date(Date hire_date) {
        this.hire_date = hire_date;
    }

    public Employees() {
    	super();
    }
    
		public Employees(Integer emp_no, Date birth_date, String first_name, String last_name, String gender,
				Date hire_date) {
			super();
			this.emp_no = emp_no;
			this.birth_date = birth_date;
			this.first_name = first_name;
			this.last_name = last_name;
			this.gender = gender;
			this.hire_date = hire_date;
		}
}