package com.senso.boot.entity;

import java.util.Date;

public class SalariesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salaries.emp_no
     *
     * @mbg.generated
     */
    private Integer emp_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salaries.from_date
     *
     * @mbg.generated
     */
    private Date from_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salaries.emp_no
     *
     * @return the value of salaries.emp_no
     *
     * @mbg.generated
     */
    public Integer getEmp_no() {
        return emp_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salaries.emp_no
     *
     * @param emp_no the value for salaries.emp_no
     *
     * @mbg.generated
     */
    public void setEmp_no(Integer emp_no) {
        this.emp_no = emp_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salaries.from_date
     *
     * @return the value of salaries.from_date
     *
     * @mbg.generated
     */
    public Date getFrom_date() {
        return from_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salaries.from_date
     *
     * @param from_date the value for salaries.from_date
     *
     * @mbg.generated
     */
    public void setFrom_date(Date from_date) {
        this.from_date = from_date;
    }
}