package com.senso.boot.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SalariesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salaries
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salaries
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salaries
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public SalariesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table salaries
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andEmp_noIsNull() {
            addCriterion("emp_no is null");
            return (Criteria) this;
        }

        public Criteria andEmp_noIsNotNull() {
            addCriterion("emp_no is not null");
            return (Criteria) this;
        }

        public Criteria andEmp_noEqualTo(Integer value) {
            addCriterion("emp_no =", value, "emp_no");
            return (Criteria) this;
        }

        public Criteria andEmp_noNotEqualTo(Integer value) {
            addCriterion("emp_no <>", value, "emp_no");
            return (Criteria) this;
        }

        public Criteria andEmp_noGreaterThan(Integer value) {
            addCriterion("emp_no >", value, "emp_no");
            return (Criteria) this;
        }

        public Criteria andEmp_noGreaterThanOrEqualTo(Integer value) {
            addCriterion("emp_no >=", value, "emp_no");
            return (Criteria) this;
        }

        public Criteria andEmp_noLessThan(Integer value) {
            addCriterion("emp_no <", value, "emp_no");
            return (Criteria) this;
        }

        public Criteria andEmp_noLessThanOrEqualTo(Integer value) {
            addCriterion("emp_no <=", value, "emp_no");
            return (Criteria) this;
        }

        public Criteria andEmp_noIn(List<Integer> values) {
            addCriterion("emp_no in", values, "emp_no");
            return (Criteria) this;
        }

        public Criteria andEmp_noNotIn(List<Integer> values) {
            addCriterion("emp_no not in", values, "emp_no");
            return (Criteria) this;
        }

        public Criteria andEmp_noBetween(Integer value1, Integer value2) {
            addCriterion("emp_no between", value1, value2, "emp_no");
            return (Criteria) this;
        }

        public Criteria andEmp_noNotBetween(Integer value1, Integer value2) {
            addCriterion("emp_no not between", value1, value2, "emp_no");
            return (Criteria) this;
        }

        public Criteria andFrom_dateIsNull() {
            addCriterion("from_date is null");
            return (Criteria) this;
        }

        public Criteria andFrom_dateIsNotNull() {
            addCriterion("from_date is not null");
            return (Criteria) this;
        }

        public Criteria andFrom_dateEqualTo(Date value) {
            addCriterionForJDBCDate("from_date =", value, "from_date");
            return (Criteria) this;
        }

        public Criteria andFrom_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("from_date <>", value, "from_date");
            return (Criteria) this;
        }

        public Criteria andFrom_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("from_date >", value, "from_date");
            return (Criteria) this;
        }

        public Criteria andFrom_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("from_date >=", value, "from_date");
            return (Criteria) this;
        }

        public Criteria andFrom_dateLessThan(Date value) {
            addCriterionForJDBCDate("from_date <", value, "from_date");
            return (Criteria) this;
        }

        public Criteria andFrom_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("from_date <=", value, "from_date");
            return (Criteria) this;
        }

        public Criteria andFrom_dateIn(List<Date> values) {
            addCriterionForJDBCDate("from_date in", values, "from_date");
            return (Criteria) this;
        }

        public Criteria andFrom_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("from_date not in", values, "from_date");
            return (Criteria) this;
        }

        public Criteria andFrom_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("from_date between", value1, value2, "from_date");
            return (Criteria) this;
        }

        public Criteria andFrom_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("from_date not between", value1, value2, "from_date");
            return (Criteria) this;
        }

        public Criteria andSalaryIsNull() {
            addCriterion("salary is null");
            return (Criteria) this;
        }

        public Criteria andSalaryIsNotNull() {
            addCriterion("salary is not null");
            return (Criteria) this;
        }

        public Criteria andSalaryEqualTo(Integer value) {
            addCriterion("salary =", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotEqualTo(Integer value) {
            addCriterion("salary <>", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryGreaterThan(Integer value) {
            addCriterion("salary >", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryGreaterThanOrEqualTo(Integer value) {
            addCriterion("salary >=", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryLessThan(Integer value) {
            addCriterion("salary <", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryLessThanOrEqualTo(Integer value) {
            addCriterion("salary <=", value, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryIn(List<Integer> values) {
            addCriterion("salary in", values, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotIn(List<Integer> values) {
            addCriterion("salary not in", values, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryBetween(Integer value1, Integer value2) {
            addCriterion("salary between", value1, value2, "salary");
            return (Criteria) this;
        }

        public Criteria andSalaryNotBetween(Integer value1, Integer value2) {
            addCriterion("salary not between", value1, value2, "salary");
            return (Criteria) this;
        }

        public Criteria andTo_dateIsNull() {
            addCriterion("to_date is null");
            return (Criteria) this;
        }

        public Criteria andTo_dateIsNotNull() {
            addCriterion("to_date is not null");
            return (Criteria) this;
        }

        public Criteria andTo_dateEqualTo(Date value) {
            addCriterionForJDBCDate("to_date =", value, "to_date");
            return (Criteria) this;
        }

        public Criteria andTo_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("to_date <>", value, "to_date");
            return (Criteria) this;
        }

        public Criteria andTo_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("to_date >", value, "to_date");
            return (Criteria) this;
        }

        public Criteria andTo_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("to_date >=", value, "to_date");
            return (Criteria) this;
        }

        public Criteria andTo_dateLessThan(Date value) {
            addCriterionForJDBCDate("to_date <", value, "to_date");
            return (Criteria) this;
        }

        public Criteria andTo_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("to_date <=", value, "to_date");
            return (Criteria) this;
        }

        public Criteria andTo_dateIn(List<Date> values) {
            addCriterionForJDBCDate("to_date in", values, "to_date");
            return (Criteria) this;
        }

        public Criteria andTo_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("to_date not in", values, "to_date");
            return (Criteria) this;
        }

        public Criteria andTo_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("to_date between", value1, value2, "to_date");
            return (Criteria) this;
        }

        public Criteria andTo_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("to_date not between", value1, value2, "to_date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table salaries
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table salaries
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}