package com.senso.boot.entity;

import java.util.Date;

public class Salaries extends SalariesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salaries.salary
     *
     * @mbg.generated
     */
    private Integer salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salaries.to_date
     *
     * @mbg.generated
     */
    private Date to_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salaries.salary
     *
     * @return the value of salaries.salary
     *
     * @mbg.generated
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salaries.salary
     *
     * @param salary the value for salaries.salary
     *
     * @mbg.generated
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salaries.to_date
     *
     * @return the value of salaries.to_date
     *
     * @mbg.generated
     */
    public Date getTo_date() {
        return to_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salaries.to_date
     *
     * @param to_date the value for salaries.to_date
     *
     * @mbg.generated
     */
    public void setTo_date(Date to_date) {
        this.to_date = to_date;
    }
}