package com.senso.boot.entity;

import java.util.Date;

public class TitlesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titles.emp_no
     *
     * @mbg.generated
     */
    private Integer emp_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titles.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titles.from_date
     *
     * @mbg.generated
     */
    private Date from_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titles.emp_no
     *
     * @return the value of titles.emp_no
     *
     * @mbg.generated
     */
    public Integer getEmp_no() {
        return emp_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titles.emp_no
     *
     * @param emp_no the value for titles.emp_no
     *
     * @mbg.generated
     */
    public void setEmp_no(Integer emp_no) {
        this.emp_no = emp_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titles.title
     *
     * @return the value of titles.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titles.title
     *
     * @param title the value for titles.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titles.from_date
     *
     * @return the value of titles.from_date
     *
     * @mbg.generated
     */
    public Date getFrom_date() {
        return from_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titles.from_date
     *
     * @param from_date the value for titles.from_date
     *
     * @mbg.generated
     */
    public void setFrom_date(Date from_date) {
        this.from_date = from_date;
    }
}