package com.senso.boot.entity;

import java.util.Date;

public class Titles extends TitlesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column titles.to_date
     *
     * @mbg.generated
     */
    private Date to_date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column titles.to_date
     *
     * @return the value of titles.to_date
     *
     * @mbg.generated
     */
    public Date getTo_date() {
        return to_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column titles.to_date
     *
     * @param to_date the value for titles.to_date
     *
     * @mbg.generated
     */
    public void setTo_date(Date to_date) {
        this.to_date = to_date;
    }
}