package com.senso.boot.mapper;

import com.senso.boot.entity.BaseUniversityCampus;
import com.senso.boot.entity.BaseUniversityCampusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseUniversityCampusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    long countByExample(BaseUniversityCampusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    int deleteByExample(BaseUniversityCampusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    int insert(BaseUniversityCampus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    int insertSelective(BaseUniversityCampus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    List<BaseUniversityCampus> selectByExample(BaseUniversityCampusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    BaseUniversityCampus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BaseUniversityCampus record, @Param("example") BaseUniversityCampusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BaseUniversityCampus record, @Param("example") BaseUniversityCampusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BaseUniversityCampus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseUniversityCampus record);
}