package com.senso.boot.mapper;

import com.senso.boot.entity.BaseCampususerStatus;
import com.senso.boot.entity.BaseCampususerStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseCampususerStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    long countByExample(BaseCampususerStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    int deleteByExample(BaseCampususerStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    int insert(BaseCampususerStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    int insertSelective(BaseCampususerStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    List<BaseCampususerStatus> selectByExample(BaseCampususerStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    BaseCampususerStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BaseCampususerStatus record, @Param("example") BaseCampususerStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BaseCampususerStatus record, @Param("example") BaseCampususerStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BaseCampususerStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_campususer_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseCampususerStatus record);
}