package com.senso.boot.mapper;

import com.senso.boot.entity.CampusUser;
import com.senso.boot.entity.CampusUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CampusUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    long countByExample(CampusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int deleteByExample(CampusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int insert(CampusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int insertSelective(CampusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    List<CampusUser> selectByExample(CampusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    CampusUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CampusUser record, @Param("example") CampusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CampusUser record, @Param("example") CampusUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CampusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CampusUser record);
}