package com.senso.boot.mapper;

import com.senso.boot.entity.SystemPage;
import com.senso.boot.entity.SystemPageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    long countByExample(SystemPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    int deleteByExample(SystemPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    int insert(SystemPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    int insertSelective(SystemPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    List<SystemPage> selectByExample(SystemPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    SystemPage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemPage record, @Param("example") SystemPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemPage record, @Param("example") SystemPageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_page
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemPage record);
}