package com.senso.boot.entity;

import java.util.ArrayList;
import java.util.List;

public class BaseUniversityCampusExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public BaseUniversityCampusExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUniversity_idIsNull() {
            addCriterion("university_id is null");
            return (Criteria) this;
        }

        public Criteria andUniversity_idIsNotNull() {
            addCriterion("university_id is not null");
            return (Criteria) this;
        }

        public Criteria andUniversity_idEqualTo(Integer value) {
            addCriterion("university_id =", value, "university_id");
            return (Criteria) this;
        }

        public Criteria andUniversity_idNotEqualTo(Integer value) {
            addCriterion("university_id <>", value, "university_id");
            return (Criteria) this;
        }

        public Criteria andUniversity_idGreaterThan(Integer value) {
            addCriterion("university_id >", value, "university_id");
            return (Criteria) this;
        }

        public Criteria andUniversity_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("university_id >=", value, "university_id");
            return (Criteria) this;
        }

        public Criteria andUniversity_idLessThan(Integer value) {
            addCriterion("university_id <", value, "university_id");
            return (Criteria) this;
        }

        public Criteria andUniversity_idLessThanOrEqualTo(Integer value) {
            addCriterion("university_id <=", value, "university_id");
            return (Criteria) this;
        }

        public Criteria andUniversity_idIn(List<Integer> values) {
            addCriterion("university_id in", values, "university_id");
            return (Criteria) this;
        }

        public Criteria andUniversity_idNotIn(List<Integer> values) {
            addCriterion("university_id not in", values, "university_id");
            return (Criteria) this;
        }

        public Criteria andUniversity_idBetween(Integer value1, Integer value2) {
            addCriterion("university_id between", value1, value2, "university_id");
            return (Criteria) this;
        }

        public Criteria andUniversity_idNotBetween(Integer value1, Integer value2) {
            addCriterion("university_id not between", value1, value2, "university_id");
            return (Criteria) this;
        }

        public Criteria andCampus_nameIsNull() {
            addCriterion("campus_name is null");
            return (Criteria) this;
        }

        public Criteria andCampus_nameIsNotNull() {
            addCriterion("campus_name is not null");
            return (Criteria) this;
        }

        public Criteria andCampus_nameEqualTo(String value) {
            addCriterion("campus_name =", value, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameNotEqualTo(String value) {
            addCriterion("campus_name <>", value, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameGreaterThan(String value) {
            addCriterion("campus_name >", value, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameGreaterThanOrEqualTo(String value) {
            addCriterion("campus_name >=", value, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameLessThan(String value) {
            addCriterion("campus_name <", value, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameLessThanOrEqualTo(String value) {
            addCriterion("campus_name <=", value, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameLike(String value) {
            addCriterion("campus_name like", value, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameNotLike(String value) {
            addCriterion("campus_name not like", value, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameIn(List<String> values) {
            addCriterion("campus_name in", values, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameNotIn(List<String> values) {
            addCriterion("campus_name not in", values, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameBetween(String value1, String value2) {
            addCriterion("campus_name between", value1, value2, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_nameNotBetween(String value1, String value2) {
            addCriterion("campus_name not between", value1, value2, "campus_name");
            return (Criteria) this;
        }

        public Criteria andCampus_addressIsNull() {
            addCriterion("campus_address is null");
            return (Criteria) this;
        }

        public Criteria andCampus_addressIsNotNull() {
            addCriterion("campus_address is not null");
            return (Criteria) this;
        }

        public Criteria andCampus_addressEqualTo(String value) {
            addCriterion("campus_address =", value, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressNotEqualTo(String value) {
            addCriterion("campus_address <>", value, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressGreaterThan(String value) {
            addCriterion("campus_address >", value, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressGreaterThanOrEqualTo(String value) {
            addCriterion("campus_address >=", value, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressLessThan(String value) {
            addCriterion("campus_address <", value, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressLessThanOrEqualTo(String value) {
            addCriterion("campus_address <=", value, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressLike(String value) {
            addCriterion("campus_address like", value, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressNotLike(String value) {
            addCriterion("campus_address not like", value, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressIn(List<String> values) {
            addCriterion("campus_address in", values, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressNotIn(List<String> values) {
            addCriterion("campus_address not in", values, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressBetween(String value1, String value2) {
            addCriterion("campus_address between", value1, value2, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_addressNotBetween(String value1, String value2) {
            addCriterion("campus_address not between", value1, value2, "campus_address");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneIsNull() {
            addCriterion("campus_telephone is null");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneIsNotNull() {
            addCriterion("campus_telephone is not null");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneEqualTo(String value) {
            addCriterion("campus_telephone =", value, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneNotEqualTo(String value) {
            addCriterion("campus_telephone <>", value, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneGreaterThan(String value) {
            addCriterion("campus_telephone >", value, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneGreaterThanOrEqualTo(String value) {
            addCriterion("campus_telephone >=", value, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneLessThan(String value) {
            addCriterion("campus_telephone <", value, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneLessThanOrEqualTo(String value) {
            addCriterion("campus_telephone <=", value, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneLike(String value) {
            addCriterion("campus_telephone like", value, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneNotLike(String value) {
            addCriterion("campus_telephone not like", value, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneIn(List<String> values) {
            addCriterion("campus_telephone in", values, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneNotIn(List<String> values) {
            addCriterion("campus_telephone not in", values, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneBetween(String value1, String value2) {
            addCriterion("campus_telephone between", value1, value2, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_telephoneNotBetween(String value1, String value2) {
            addCriterion("campus_telephone not between", value1, value2, "campus_telephone");
            return (Criteria) this;
        }

        public Criteria andCampus_faxIsNull() {
            addCriterion("campus_fax is null");
            return (Criteria) this;
        }

        public Criteria andCampus_faxIsNotNull() {
            addCriterion("campus_fax is not null");
            return (Criteria) this;
        }

        public Criteria andCampus_faxEqualTo(String value) {
            addCriterion("campus_fax =", value, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxNotEqualTo(String value) {
            addCriterion("campus_fax <>", value, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxGreaterThan(String value) {
            addCriterion("campus_fax >", value, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxGreaterThanOrEqualTo(String value) {
            addCriterion("campus_fax >=", value, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxLessThan(String value) {
            addCriterion("campus_fax <", value, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxLessThanOrEqualTo(String value) {
            addCriterion("campus_fax <=", value, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxLike(String value) {
            addCriterion("campus_fax like", value, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxNotLike(String value) {
            addCriterion("campus_fax not like", value, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxIn(List<String> values) {
            addCriterion("campus_fax in", values, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxNotIn(List<String> values) {
            addCriterion("campus_fax not in", values, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxBetween(String value1, String value2) {
            addCriterion("campus_fax between", value1, value2, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andCampus_faxNotBetween(String value1, String value2) {
            addCriterion("campus_fax not between", value1, value2, "campus_fax");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNull() {
            addCriterion("isdeleted is null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNotNull() {
            addCriterion("isdeleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedEqualTo(Boolean value) {
            addCriterion("isdeleted =", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotEqualTo(Boolean value) {
            addCriterion("isdeleted <>", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThan(Boolean value) {
            addCriterion("isdeleted >", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isdeleted >=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThan(Boolean value) {
            addCriterion("isdeleted <", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("isdeleted <=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIn(List<Boolean> values) {
            addCriterion("isdeleted in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotIn(List<Boolean> values) {
            addCriterion("isdeleted not in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("isdeleted between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isdeleted not between", value1, value2, "isdeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_university_campus
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_university_campus
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}