package com.senso.boot.entity;

import java.util.Date;

public class CampusUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.fname
     *
     * @mbg.generated
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.mname
     *
     * @mbg.generated
     */
    private String mname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.lname
     *
     * @mbg.generated
     */
    private String lname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.lastlogin
     *
     * @mbg.generated
     */
    private Date lastlogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.clientstatus
     *
     * @mbg.generated
     */
    private Byte clientstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.id
     *
     * @return the value of campus_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.id
     *
     * @param id the value for campus_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.username
     *
     * @return the value of campus_user.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.username
     *
     * @param username the value for campus_user.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.email
     *
     * @return the value of campus_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.email
     *
     * @param email the value for campus_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.pwd
     *
     * @return the value of campus_user.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.pwd
     *
     * @param pwd the value for campus_user.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.create_time
     *
     * @return the value of campus_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.create_time
     *
     * @param create_time the value for campus_user.create_time
     *
     * @mbg.generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.fname
     *
     * @return the value of campus_user.fname
     *
     * @mbg.generated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.fname
     *
     * @param fname the value for campus_user.fname
     *
     * @mbg.generated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.mname
     *
     * @return the value of campus_user.mname
     *
     * @mbg.generated
     */
    public String getMname() {
        return mname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.mname
     *
     * @param mname the value for campus_user.mname
     *
     * @mbg.generated
     */
    public void setMname(String mname) {
        this.mname = mname == null ? null : mname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.lname
     *
     * @return the value of campus_user.lname
     *
     * @mbg.generated
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.lname
     *
     * @param lname the value for campus_user.lname
     *
     * @mbg.generated
     */
    public void setLname(String lname) {
        this.lname = lname == null ? null : lname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.lastlogin
     *
     * @return the value of campus_user.lastlogin
     *
     * @mbg.generated
     */
    public Date getLastlogin() {
        return lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.lastlogin
     *
     * @param lastlogin the value for campus_user.lastlogin
     *
     * @mbg.generated
     */
    public void setLastlogin(Date lastlogin) {
        this.lastlogin = lastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.clientstatus
     *
     * @return the value of campus_user.clientstatus
     *
     * @mbg.generated
     */
    public Byte getClientstatus() {
        return clientstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.clientstatus
     *
     * @param clientstatus the value for campus_user.clientstatus
     *
     * @mbg.generated
     */
    public void setClientstatus(Byte clientstatus) {
        this.clientstatus = clientstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.phone
     *
     * @return the value of campus_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.phone
     *
     * @param phone the value for campus_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}