package com.senso.boot.entity;

public class SystemRolepage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rolepage.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rolepage.roleid
     *
     * @mbg.generated
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_rolepage.pageid
     *
     * @mbg.generated
     */
    private Integer pageid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rolepage.id
     *
     * @return the value of system_rolepage.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rolepage.id
     *
     * @param id the value for system_rolepage.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rolepage.roleid
     *
     * @return the value of system_rolepage.roleid
     *
     * @mbg.generated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rolepage.roleid
     *
     * @param roleid the value for system_rolepage.roleid
     *
     * @mbg.generated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_rolepage.pageid
     *
     * @return the value of system_rolepage.pageid
     *
     * @mbg.generated
     */
    public Integer getPageid() {
        return pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_rolepage.pageid
     *
     * @param pageid the value for system_rolepage.pageid
     *
     * @mbg.generated
     */
    public void setPageid(Integer pageid) {
        this.pageid = pageid;
    }
}