package com.senso.boot.entity;

public class SystemUserrole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_userrole.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_userrole.rolename
     *
     * @mbg.generated
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_userrole.id
     *
     * @return the value of system_userrole.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_userrole.id
     *
     * @param id the value for system_userrole.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_userrole.rolename
     *
     * @return the value of system_userrole.rolename
     *
     * @mbg.generated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_userrole.rolename
     *
     * @param rolename the value for system_userrole.rolename
     *
     * @mbg.generated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }
}